services:
  frontend:
    image: ghcr.io/iamapoorv476/my-excildrawapp/frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3001
      - NEXT_PUBLIC_WS_URL=ws://ws:8080
    depends_on:
      - api
      - ws
    networks:
      - excildraw-net
  api:
    image: ghcr.io/iamapoorv476/my-excildrawapp/api:latest
    ports:
      -"3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition:service_healthy
      migration:
        condition:service_completed_successfully
    networks:
      - excildraw-net
  ws:
    image: ghcr.io/iamapoorv476/my-excildrawapp/ws:latest
    ports:
      -"8080-8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition:service_healthy
      migration:
        condition:service_completed_successfully
    networks:
      - excildraw-net
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      -postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - excildraw-net

  migration:
    image: ghcr.io/iamapoorv476/my-excildrawapp/api:latest
    command: >
      sh -c "
        echo 'Waiting for database...'
        sleep 5 &&
        cd packages/db &&
        prisma migrate deploy --schema=./prisma/schema.prisma
      "
        
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - excildraw-net

networks:
  excildraw-net:
    driver: bridge

volumes:
  postgres-data:
